Repository uni-bremen-agst/SEE, pull requests merged in 2023-08, with the labels that each got.

#631 Actions: Warn if OpenXR gets enabled
  .gitattributes
  Assets/XR/Loaders.meta
  Assets/XR/Loaders/Open VR Loader.asset
  Assets/XR/Loaders/Open VR Loader.asset.meta
  Assets/XR/Loaders/Open XR Loader No Pre Init.asset
  Assets/XR/Loaders/Open XR Loader No Pre Init.asset.meta
  Assets/XR/Loaders/Open XR Loader.asset
  Assets/XR/Loaders/Open XR Loader.asset.meta
  Assets/XR/Loaders/Windows MR Loader.asset
  Assets/XR/Loaders/Windows MR Loader.asset.meta
  Assets/XR/Settings.meta
  Assets/XR/Settings/Open XR Package Settings.asset
  Assets/XR/Settings/Open XR Package Settings.asset.meta
  Assets/XR/Settings/OpenXR Editor Settings.asset
  Assets/XR/Settings/OpenXR Editor Settings.asset.meta
  Assets/XR/Settings/Windows MR Package Settings.asset
  Assets/XR/Settings/Windows MR Package Settings.asset.meta
  Assets/XR/XRGeneralSettings.asset
  Assets/XR/XRGeneralSettings.asset.meta
  GitScripts/check_for_bad_patterns.py
  GitScripts/check_for_lfs_files.sh
Labels: no release

#629 599 - Action to add Edges to the Architecture Graph to solve Divergences
  Assets/Editor/ArchitectureInteractionEditor.cs
  Assets/Resources/Materials/MirrorMaterial/Mirror Render Texture.renderTexture
  Assets/SEE/Controls/Actions/AcceptDivergenceAction.cs
  Assets/SEE/Controls/Actions/AcceptDivergenceAction.cs.meta
  Assets/SEE/Controls/Actions/ActionStateType.cs
  Assets/SEE/Controls/Actions/ActionStateTypes.cs
  Assets/SEE/Controls/Actions/AddEdgeAction.cs
  Assets/SEE/Controls/Actions/AddNodeAction.cs
  Assets/SEE/Controls/Actions/DeleteAction.cs
  Assets/SEE/Controls/Actions/MoveAction.cs
  Assets/SEE/Controls/Interactables/InteractableObject.cs
  Assets/SEE/DataModel/DG/Edge.cs
  Assets/SEE/Game/ArchitectureInteraction.cs
  Assets/SEE/Game/EdgeRenderer.cs
  Assets/SEE/Game/Evolution/EvolutionRenderer.cs
  Assets/SEE/Game/GameNodeScaler.cs
  Assets/SEE/Game/IGraphRenderer.cs
  Assets/SEE/Game/InteractionDecorator.cs
  Assets/SEE/Game/SceneManipulation.meta
  Assets/SEE/Game/SceneManipulation/AcceptDivergence.cs
  Assets/SEE/Game/SceneManipulation/AcceptDivergence.cs.meta
  Assets/SEE/Game/SceneManipulation/GameEdgeAdder.cs
  Assets/SEE/Game/SceneManipulation/GameEdgeAdder.cs.meta
  Assets/SEE/Game/SceneManipulation/GameElementDeleter.cs
  Assets/SEE/Game/SceneManipulation/GameElementDeleter.cs.meta
  Assets/SEE/Game/SceneManipulation/GameNodeAdder.cs
  Assets/SEE/Game/SceneManipulation/GameNodeAdder.cs.meta
  Assets/SEE/Game/SceneManipulation/GameNodeMover.cs
  Assets/SEE/Game/SceneManipulation/GameNodeMover.cs.meta
  Assets/SEE/Game/SceneManipulation/GameObjectFader.cs
  Assets/SEE/Game/SceneManipulation/GameObjectFader.cs.meta
  Assets/SEE/Game/SceneManipulation/GameObjectFlasher.cs
  Assets/SEE/Game/SceneManipulation/GameObjectFlasher.cs.meta
  Assets/SEE/Game/SceneManipulation/SceneManipulation.cs
  Assets/SEE/Game/SceneManipulation/SceneManipulation.cs.meta
  Assets/SEE/Net/Actions/AcceptDivergenceNetAction.cs
  Assets/SEE/Net/Actions/AcceptDivergenceNetAction.cs.meta
  Assets/SEE/Net/Actions/AddEdgeNetAction.cs
  Assets/SEE/Net/Actions/AddNodeNetAction.cs
  Assets/SEE/Net/Actions/DeleteNetAction.cs
  Assets/SEE/Net/Actions/MoveNetAction.cs
  Assets/SEE/Net/Actions/PutOnAndFitNetAction.cs
  Assets/SEE/Net/Actions/ReviveNetAction.cs
  Assets/SEE/Net/Actions/SetParentNetAction.cs
  Assets/SEE/Net/Actions/VersionNetAction.cs
  Assets/SEE/Tools/ReflexionAnalysis/Incremental.cs
  Assets/SEE/Tools/ReflexionAnalysis/ReflexionAnalysis.cs
  Assets/SEE/Tools/ReflexionAnalysis/ReflexionGraph.cs
  Assets/SEE/Utils/ActionHistory.cs
  Packages/packages-lock.json
Labels: bachelorproject

#624 Multiplayer FaceCam
  .gitattributes
  Assets/Plugins/FaceCam.meta
  Assets/Plugins/FaceCam/ExampleMaterial.mat
  Assets/Plugins/FaceCam/ExampleMaterial.mat.meta
  Assets/Plugins/FaceCam/LoadingIcon.png
  Assets/Plugins/FaceCam/LoadingIcon.png.meta
  Assets/Resources/Prefabs/FaceCam.meta
  Assets/Resources/Prefabs/FaceCam/FaceCam.prefab
  Assets/Resources/Prefabs/FaceCam/FaceCam.prefab.meta
  Assets/SEE/Controls/KeyBindings.cs
  Assets/SEE/Controls/SEEInput.cs
  Assets/SEE/Game/Evolution/EvolutionRendererAddNodes.cs
  Assets/SEE/Game/Worlds/PlayerSpawner.cs
  Assets/SEE/SEE.asmdef
  Assets/SEE/Tools/FaceCam.meta
  Assets/SEE/Tools/FaceCam/FaceCam.cs
  Assets/SEE/Tools/FaceCam/FaceCam.cs.meta
  Assets/SEE/Utils/Destroyer.cs
  Assets/StreamingAssets/DlibFaceLandmarkDetector.meta
  Assets/StreamingAssets/DlibFaceLandmarkDetector/sp_human_face_17.dat
  Assets/StreamingAssets/DlibFaceLandmarkDetector/sp_human_face_17.dat.meta
  Assets/StreamingAssets/DlibFaceLandmarkDetector/sp_human_face_17_for_mobile.dat
  Assets/StreamingAssets/DlibFaceLandmarkDetector/sp_human_face_17_for_mobile.dat.meta
  Assets/StreamingAssets/DlibFaceLandmarkDetector/sp_human_face_6.dat
  Assets/StreamingAssets/DlibFaceLandmarkDetector/sp_human_face_6.dat.meta
  Assets/StreamingAssets/DlibFaceLandmarkDetector/sp_human_face_68.dat
  Assets/StreamingAssets/DlibFaceLandmarkDetector/sp_human_face_68.dat.meta
  Assets/StreamingAssets/DlibFaceLandmarkDetector/sp_human_face_68_for_mobile.dat
  Assets/StreamingAssets/DlibFaceLandmarkDetector/sp_human_face_68_for_mobile.dat.meta
  ProjectSettings/ProjectSettings.asset
Labels: enhancement, bachelorproject

#635 Actions: Allow `Object.Destroy()` calls in Destroyer.cs
  GitScripts/check_for_bad_patterns.py
Labels: no release
