Repository uni-bremen-agst/SEE, pull requests merged in 2023-12, with the labels that each got.

#677 676 diffcity
  Assets/SEE/Game/City/DiffCity.cs
  Assets/SEE/Game/City/DiffCity.cs.meta
  Assets/SEETests/TestConfigIO.cs
  Assets/Scenes/SEEWorld.unity
  Assets/StreamingAssets/JLGExample/analyze.bat.meta
  Assets/XR/Settings/Open XR Package Settings.asset
  ProjectSettings/ProjectSettings.asset
Labels: enhancement

#681 TreeView: Filtering, Sorting, Grouping
  .github/workflows/main.yml
  Assets/Resources/Prefabs/UI/PopupMenu.prefab
  Assets/Resources/Prefabs/UI/PopupMenuHeading.prefab
  Assets/Resources/Prefabs/UI/PopupMenuHeading.prefab.meta
  Assets/Resources/Prefabs/UI/TreeView.prefab
  Assets/SEE/Controls/Actions/ContextMenuAction.cs
  Assets/SEE/Controls/Actions/MoveAction.cs
  Assets/SEE/DataModel/DG/Attributable.cs
  Assets/SEE/DataModel/DG/Graph.cs
  Assets/SEE/DataModel/DG/GraphElementsAttributes.cs
  Assets/SEE/DataModel/DG/GraphExtensions.cs
  Assets/SEE/DataModel/DG/GraphSearch.cs.meta
  Assets/SEE/DataModel/GraphSearch.meta
  Assets/SEE/DataModel/GraphSearch/GraphFilter.cs
  Assets/SEE/DataModel/GraphSearch/GraphFilter.cs.meta
  Assets/SEE/DataModel/GraphSearch/GraphSearch.cs
  Assets/SEE/DataModel/GraphSearch/GraphSearch.cs.meta
  Assets/SEE/DataModel/GraphSearch/GraphSorter.cs
  Assets/SEE/DataModel/GraphSearch/GraphSorter.cs.meta
  Assets/SEE/DataModel/GraphSearch/IGraphModifier.cs
  Assets/SEE/DataModel/GraphSearch/IGraphModifier.cs.meta
  Assets/SEE/Game/Avatars/PersonalAssistantSpeechInput.cs
  Assets/SEE/Game/City/ReflexionVisualization.cs
  Assets/SEE/Game/CityRendering/AbstractLayoutNode.cs
  Assets/SEE/Net/Dashboard/DashboardRetriever.cs
  Assets/SEE/Net/Dashboard/DashboardVersion.cs
  Assets/SEE/UI/Menu/NestedMenu.cs
  Assets/SEE/UI/PopupMenu/PopupMenu.cs
  Assets/SEE/UI/PopupMenu/PopupMenuAction.cs
  Assets/SEE/UI/PopupMenu/PopupMenuEntry.cs
  Assets/SEE/UI/PopupMenu/PopupMenuEntry.cs.meta
  Assets/SEE/UI/Window/DesktopWindowSpace.cs
  Assets/SEE/UI/Window/TreeWindow/DesktopTreeWindow.cs
  Assets/SEE/UI/Window/TreeWindow/TreeWindow.cs
  Assets/SEE/UI/Window/TreeWindow/TreeWindowContextMenu.cs
  Assets/SEE/UI/Window/TreeWindow/TreeWindowContextMenu.cs.meta
  Assets/SEE/UI/Window/TreeWindow/TreeWindowGrouper.cs
  Assets/SEE/UI/Window/TreeWindow/TreeWindowGrouper.cs.meta
  Assets/SEE/UI/Window/WindowSpace.cs
  Assets/SEE/Utils/CollectionExtensions.cs
  Assets/SEE/Utils/CollectionExtensions.cs.meta
  Assets/SEE/Utils/DefaultDictionary.cs
  Assets/SEE/Utils/DefaultDictionary.cs.meta
  Assets/SEE/Utils/Icons.cs
  Assets/SEE/Utils/Icons.cs.meta
  Assets/SEE/Utils/ListExtensions.cs
  Assets/SEE/Utils/MathExtensions.cs
  Assets/Scenes/SEEWorld.unity
  Axivion/axivion-jenkins.bat
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectVersion.txt
  README.md
Labels: enhancement, Improvement

#675 Updated keybindings: they are now changeable.
  Assets/Resources/Prefabs/UI/KeyBindingContent.prefab
  Assets/Resources/Prefabs/UI/KeyBindingContent.prefab.meta
  Assets/Resources/Prefabs/UI/ScrollPrefab.prefab
  Assets/Resources/Prefabs/UI/ScrollPrefab.prefab.meta
  Assets/Resources/Prefabs/UI/SettingsMenu.prefab
  Assets/SEE/Controls/KeyAction.cs
  Assets/SEE/Controls/KeyAction.cs.meta
  Assets/SEE/Controls/KeyActionCategory.cs
  Assets/SEE/Controls/KeyActionCategory.cs.meta
  Assets/SEE/Controls/KeyActionDescriptor.cs
  Assets/SEE/Controls/KeyActionDescriptor.cs.meta
  Assets/SEE/Controls/KeyBindings.cs
  Assets/SEE/Controls/SEEInput.cs
  Assets/SEE/Controls/SceneSettings.cs
  Assets/SEE/Game/City/SEEJLGCityAnimation.cs
  Assets/SEE/UI/HelpSystem/HelpSystemMenu.cs
  Assets/SEE/UI/SettingsMenu.cs
Labels: Improvement

#684 Loading spinner
  Assets/Plugins/AmplifyShaderEditor/Plugins/Editor/Templates/TemplateMenuItems.cs
  Assets/Plugins/Modern UI Pack/Fonts/OpenSans-ExtraBold SDF.asset
  Assets/Plugins/ZFBrowser/Demo/Standard Assets/Prototyping/Materials/YellowSmooth.mat
  Assets/Resources/Fonts/Hack-Regular SDF.asset
  Assets/Resources/Materials/GlowingCircle.mat
  Assets/Resources/Materials/GlowingCircle.mat.meta
  Assets/Resources/Prefabs/Players/DesktopPlayer.prefab
  Assets/Resources/Prefabs/UI/LoadingSpinner.prefab
  Assets/Resources/Prefabs/UI/LoadingSpinner.prefab.meta
  Assets/SEE/Game/City/EdgeMeshScheduler.cs
  Assets/SEE/Game/City/SEECity.cs
  Assets/SEE/Game/Evolution/EvolutionRenderer.cs
  Assets/SEE/Game/Evolution/EvolutionRendererLayout.cs
  Assets/SEE/UI/LoadingSpinner.cs
  Assets/SEE/UI/LoadingSpinner.cs.meta
  Assets/SEE/UI/Tooltip/Tooltip.cs
  Assets/SEE/Utils/AsyncUtils.cs
  Assets/SEE/Utils/AsyncUtils.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/ProjectSettings.asset
Labels: enhancement
