Repository uni-bremen-agst/SEE, pull requests merged in 2023-10, with the labels that each got.

#643 CI: Fix build creation
  .github/workflows/main.yml
  Assets/Editor/BuildScript.cs
  Assets/Editor/BuildScript.cs.meta
Labels: no release

#646 642 face cam
  Assets/Resources/Player.prefab
  Assets/Resources/Player.prefab.meta
  Assets/Resources/Prefabs/Players/BaseAvatar.prefab
  Assets/Resources/Prefabs/Players/FaceCam.prefab
  Assets/Resources/Prefabs/Players/FaceCam.prefab.meta
  Assets/Resources/Prefabs/Players/Male1.prefab
  Assets/Resources/Prefabs/Players/Male2.prefab
  Assets/Resources/TracingDisplay.prefab
  Assets/SEE/Controls/Actions/LocalPlayerActions.cs
  Assets/SEE/Controls/Actions/ShowLabel.cs
  Assets/SEE/Controls/SceneSettings.cs
  Assets/SEE/Game/Avatars/AvatarAdapter.cs
  Assets/SEE/Game/HolisticMetrics/WidgetsManager.cs
  Assets/SEE/Game/LabelAttributes.cs
  Assets/SEE/Game/LocalPlayer.cs
  Assets/SEE/Game/LocalPlayer.cs.meta
  Assets/SEE/Game/Operator/LabelOperator.cs
  Assets/SEE/Game/Operator/NodeOperator.cs
  Assets/SEE/Game/Worlds/PlayerSpawner.cs
  Assets/SEE/GameObjects/Menu/PlayerMenu.cs
  Assets/SEE/Tools/FaceCam/FaceCam.cs
Labels: bug

#648 Tree View: Color, animations, click-to-find
  Assets/Resources/External/FontAwesome/otfs/Font Awesome 6 Free-Solid-900 SDF.asset
  Assets/Resources/Prefabs/UI/TreeViewItem.prefab
  Assets/Resources/Prefabs/UI/TreeViewItem.prefab.meta
  Assets/SEE/Controls/Actions/MoveAction.cs
  Assets/SEE/Controls/Actions/NodeManipulationAction.cs
  Assets/SEE/Controls/Actions/ShowEdgesAction.cs
  Assets/SEE/Controls/Actions/ShowLabel.cs
  Assets/SEE/Controls/Actions/ShuffleAction.cs
  Assets/SEE/Controls/Actions/ZoomAction.cs
  Assets/SEE/Controls/Actions/ZoomActionDesktop.cs
  Assets/SEE/Controls/Interactables/InteractableObject.cs
  Assets/SEE/DataModel/DG/GraphElementExtensions.cs
  Assets/SEE/DataModel/DG/GraphElementExtensions.cs.meta
  Assets/SEE/Game/City/ReflexionVisualization.cs
  Assets/SEE/Game/CityRendering/NodeRenderer.cs
  Assets/SEE/Game/Evolution/EvolutionRendererAddEdges.cs
  Assets/SEE/Game/Evolution/EvolutionRendererAddNodes.cs
  Assets/SEE/Game/Evolution/EvolutionRendererAdjust.cs
  Assets/SEE/Game/Evolution/EvolutionRendererMove.cs
  Assets/SEE/Game/Evolution/EvolutionRendererRemove.cs
  Assets/SEE/Game/Operator/AbstractOperator.cs
  Assets/SEE/Game/Operator/AndCombinedOperationCallback.cs
  Assets/SEE/Game/Operator/DummyOperationCallback.cs
  Assets/SEE/Game/Operator/EdgeOperator.cs
  Assets/SEE/Game/Operator/GraphElementOperator.cs
  Assets/SEE/Game/Operator/IOperationCallback.cs
  Assets/SEE/Game/Operator/NodeOperator.cs
  Assets/SEE/Game/Operator/NotificationOperator.cs
  Assets/SEE/Game/Operator/TweenOperationCallback.cs
  Assets/SEE/Game/SceneManipulation/GameNodeMover.cs
  Assets/SEE/Game/SceneManipulation/GameObjectFlasher.cs
  Assets/SEE/Game/SceneManipulation/GameObjectFlasher.cs.meta
  Assets/SEE/GameObjects/GameObjectExtensions.cs
  Assets/SEE/GameObjects/MarkerFactory.cs
  Assets/SEE/GameObjects/Menu/SearchMenu.cs
  Assets/SEE/Net/Actions/RotateNodeNetAction.cs
  Assets/SEE/Net/Actions/ScaleNodeNetAction.cs
  Assets/SEE/Net/Actions/ShuffleNetAction.cs
  Assets/SEE/Net/Actions/ZoomNetAction.cs
  Assets/SEE/UI/ConfigMenu/ConfigMenu.cs
  Assets/SEE/UI/ConfigMenu/ConfigMenuFactory.cs
  Assets/SEE/UI/ConfigMenu/DynamicUIBehaviour.cs
  Assets/SEE/UI/Menu/Desktop/SimpleListMenuDesktop.cs
  Assets/SEE/UI/Notification/Notification.cs
  Assets/SEE/UI/PropertyDialog/ButtonProperty.cs
  Assets/SEE/UI/PropertyDialog/SelectionProperty.cs
  Assets/SEE/UI/PropertyDialog/StringProperty.cs
  Assets/SEE/UI/StateIndicator/HideStateIndicator.cs
  Assets/SEE/UI/Window/TreeWindow/DesktopTreeWindow.cs
  Assets/SEE/Utils/ColorExtensions.cs
  Assets/SEE/Utils/PointerHelper.cs
  Assets/XR/Settings/Open XR Package Settings.asset
  Packages/manifest.json
  Packages/packages-lock.json
Labels: Improvement

#649 Fix check_for_lfs_files.sh not working in some shells
  GitScripts/check_for_lfs_files.sh
Labels: no release

#656 TreeView: Search and smaller improvements
  Assets/Plugins/Modern UI Pack/Textures/Border/Rounded/256px/Rounded Filled 256px Dark.asset
  Assets/Plugins/Modern UI Pack/Textures/Border/Rounded/256px/Rounded Filled 256px Dark.asset.meta
  Assets/Plugins/Modern UI Pack/Textures/Border/Rounded/256px/Rounded Filled 256px Dark.png
  Assets/Plugins/Modern UI Pack/Textures/Border/Rounded/256px/Rounded Filled 256px Dark.png.meta
  Assets/Resources/Prefabs/Players/DesktopPlayer.prefab
  Assets/Resources/Prefabs/UI/TreeView.prefab
  Assets/Resources/Prefabs/UI/TreeViewItem.prefab
  Assets/Resources/Prefabs/UI/TreeViewItem.prefab.meta
  Assets/SEE/DataModel/DG/GraphElementExtensions.cs
  Assets/SEE/DataModel/DG/GraphSearch.cs
  Assets/SEE/DataModel/DG/GraphSearch.cs.meta
  Assets/SEE/Game/GraphElementIDMap.cs
  Assets/SEE/Game/Operator/NodeOperator.cs
  Assets/SEE/GameObjects/Menu/SearchMenu.cs
  Assets/SEE/GameObjects/Menu/SearchMenu.cs.meta
  Assets/SEE/UI/Menu/NestedMenu.cs
  Assets/SEE/UI/PlatformDependentComponent.cs
  Assets/SEE/UI/Window/TreeWindow/DesktopTreeWindow.cs
  Assets/SEE/UI/Window/TreeWindow/TreeWindow.cs
  Assets/SEE/Utils/ColorExtensions.cs
  Assets/SEE/Utils/UIExtensions.cs
  Assets/SEE/Utils/UIExtensions.cs.meta
  Data/GXL/SEE/SEE.cfg
Labels: enhancement
