Repository uni-bremen-agst/SEE, pull requests merged in 2024-01, with the labels that each got.

#688 Added the ability to save keybindings.
  .gitignore
  Assets/SEE/Controls/KeyAction.cs
  Assets/SEE/Controls/KeyActionCategory.cs
  Assets/SEE/Controls/KeyActionDescriptor.cs
  Assets/SEE/Controls/KeyBindings.cs
  Assets/SEE/Controls/KeyMap.cs
  Assets/SEE/Controls/KeyMap.cs.meta
  Assets/SEE/Controls/SEEInput.cs
  Assets/SEE/Game/City/SEEJLGCityAnimation.cs
  Assets/SEE/Net/Dashboard/DashboardRetriever.cs
  Assets/SEE/SEE.cs
  Assets/SEE/UI/SettingsMenu.cs
  Assets/SEETests/TestKeyMap.cs
  Assets/SEETests/TestKeyMap.cs.meta
Labels: enhancement

#691 Delete files created by tests
  Assets/SEE/DataModel/DG/IO/GraphWriter.cs
  Assets/SEE/Utils/FileIO.cs
  Assets/SEETests/TestConfigIO.cs
  Assets/SEETests/TestGraphIO.cs
  Assets/SEETests/TestKeyMap.cs
  Assets/SEETests/TestLayoutIO.cs
Labels: quality control

#692 Scrollable PopupMenu and Bugfixes
  Assets/Resources/Prefabs/UI/PopupMenu.prefab
  Assets/Resources/Prefabs/UI/PopupMenuButton.prefab
  Assets/Resources/Prefabs/UI/PopupMenuHeading.prefab
  Assets/SEE/Controls/Actions/ContextMenuAction.cs
  Assets/SEE/Controls/Actions/ShowTree.cs
  Assets/SEE/Controls/WindowSpaceManager.cs
  Assets/SEE/UI/PopupMenu/PopupMenu.cs
  Assets/SEE/UI/Window/TreeWindow/TreeWindowContextMenu.cs
  Assets/SEE/UI/Window/WindowSpace.cs
  Assets/SEE/Utils/Icons.cs
  Assets/SEETests/TestDashboard.cs
Labels: bug, Improvement

#690 672 code coverage should be visible
  .gitignore
  Assets/SEE/Controls/Actions/ContextMenuAction.cs
  Assets/SEE/Controls/Actions/ShowCodeAction.cs
  Assets/SEE/DataModel/DG/Attributable.cs
  Assets/SEE/DataModel/DG/GraphElement.cs
  Assets/SEE/DataModel/DG/IO/JaCoCoImporter.cs
  Assets/SEE/DataModel/DG/IO/JaCoCoImporter.cs.meta
  Assets/SEE/DataModel/DG/IO/MetricImporter.cs
  Assets/SEE/DataModel/DG/Node.cs
  Assets/SEE/DataModel/DG/SourceRange.meta
  Assets/SEE/DataModel/DG/SourceRange/FileRanges.cs
  Assets/SEE/DataModel/DG/SourceRange/FileRanges.cs.meta
  Assets/SEE/DataModel/DG/SourceRange/Range.cs
  Assets/SEE/DataModel/DG/SourceRange/Range.cs.meta
  Assets/SEE/DataModel/DG/SourceRange/SortedRanges.cs
  Assets/SEE/DataModel/DG/SourceRange/SortedRanges.cs.meta
  Assets/SEE/DataModel/DG/SourceRange/SourceRangeIndex.cs
  Assets/SEE/DataModel/DG/SourceRange/SourceRangeIndex.cs.meta
  Assets/SEE/DataModel/DG/StandardNames.cs
  Assets/SEE/Game/City/SEECity.cs
  Assets/SEE/Game/City/SEEReflexionCity.cs
  Assets/SEE/IDE/IDEIntegration.cs
  Assets/SEE/Tools/ReflexionAnalysis/ReflexionAnalysis.cs
  Assets/SEE/Utils/CollectionExtensions.cs
  Assets/SEETests/TestConfigIO.cs
  Assets/SEETests/TestGraphBase.cs
  Assets/SEETests/TestJacocoImporter.cs
  Assets/SEETests/TestJacocoImporter.cs.meta
  Assets/SEETests/TestSortedRanges.cs
  Assets/SEETests/TestSortedRanges.cs.meta
  Assets/SEETests/TestSourceRangeIndex.cs
  Assets/SEETests/TestSourceRangeIndex.cs.meta
  Assets/StreamingAssets/JLGExample/CodeFacts.gxl.xz
  Assets/StreamingAssets/JLGExample/CodeFacts.jlg
  Assets/StreamingAssets/JLGExample/Main.java
  Assets/StreamingAssets/JLGExample/Unterordner/UnterOrdnerTest.java
  Assets/StreamingAssets/JLGExample/analyze.bat
  Assets/StreamingAssets/JLGExample/counter.meta
  Assets/StreamingAssets/JLGExample/counter/CountConsonants.java
  Assets/StreamingAssets/JLGExample/counter/CountConsonants.java.meta
  Assets/StreamingAssets/JLGExample/counter/CountToAThousand.java
  Assets/StreamingAssets/JLGExample/counter/CountToAThousand.java.meta
  Assets/StreamingAssets/JLGExample/counter/CountVowels.java
  Assets/StreamingAssets/JLGExample/counter/CountVowels.java.meta
  Assets/StreamingAssets/JLGExample/counter/unterordner.meta
  Assets/StreamingAssets/JLGExample/counter/unterordner/UnterOrdnerTest.java
  Assets/StreamingAssets/JLGExample/counter/unterordner/UnterOrdnerTest.java.meta
  Assets/StreamingAssets/JLGExample/jacoco.xml
  Assets/StreamingAssets/JLGExample/jacoco.xml.meta
Labels: enhancement
